Repository coronasafe/dashboard, pull requests merged in 2021-06, with the labels that each got.

#146 Revamped UI for capacity table information.
  src/components/Cards/CapacityCard.js
  src/components/DistrictDashboard/Capacity.js
  tailwind.config.js
Labels: enhancement

#148 Rearrange order of the cards in patient dashboard
  src/components/DistrictDashboard/Patient.js
  src/utils/constants.js
Labels: tested

#157 Debouncing in facility search
  src/components/DistrictDashboard/Capacity.js
Labels: enhancement

#145 Add facility page
  src/components/Cards/CapacityCard.js
  src/components/Chart/RadialCard.js
  src/components/DistrictDashboard/Capacity.js
  src/components/DistrictDashboard/GenericTable.js
  src/components/DistrictDashboard/OxygenMonitor.js
  src/components/DistrictDashboard/Patient.js
  src/containers/Main.js
  src/pages/Facility.js
  src/routes/index.js
  src/utils/api.js
Labels: test failed

#172 Revamp oxygen UI
  src/components/Cards/OxygenCard.js
  src/components/DistrictDashboard/OxygenMonitor.js
Labels: enhancement
